# -*- coding: utf-8 -*-
"""Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x7qJ8ugyv8zVoVzQuTAp9OkTiCnFr5Fs
"""

num1 = float(input("Enter num1: "))
num2 = float(input("Enter num2: "))
operator = input("Enter the mathematical operator: ")

if operator == '+':
    print("Result:", num1 + num2)

elif operator == '-':
    print("Result:", num1 - num2)

elif operator == '*':
    print("Result:", num1 * num2)

elif operator == '/':
    if num2 != 0:
        print("Result:", num1 / num2)
    else:
        print("Cannot divide by zero")

else:
    print("Invalid operator")