# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1snUQRonVNLVpodCgXfUAAglBYagiYkD_
"""

N = int(input())
for i in range(1, N + 1):
    if i > 20:
        break
    if i % 5 == 0:
        continue
    print(i, end=" ")

firstname = input()
lastname = input()
age = input()
username = firstname[:3].lower() + "_" + lastname.lower() + age
print("username =",username)

text = input()
vowelcount = 0
cleaned = ""
for ch in text:
    if ch == ".":
        break
    cleaned += ch
for ch in text:
    if ch.lower() in "aeiou":
        vowelcount += 1
print("Vowel count:", vowelcount)
print("Cleaned sentence:", cleaned.upper())